/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
} from "class-validator";
import { ProjectCreateNestedManyWithoutCityHallsInput } from "./ProjectCreateNestedManyWithoutCityHallsInput";
import { Type } from "class-transformer";
import { UserCreateNestedManyWithoutCityHallsInput } from "./UserCreateNestedManyWithoutCityHallsInput";

@InputType()
class CityHallCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
    example: 37.060899,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  defaultLatitude?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
    example: -8.064873,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  defaultLongitude?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
    example: "https://firebasestorage.googleapis.com/v0/b/smartroads-gmaps-dev.firebasestorage.app/o/geopackages%2Ffaro.gpkg?alt=media&token=...",
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gisFileUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
    example: "1.0",
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gisFileVersion?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProjectCreateNestedManyWithoutCityHallsInput,
  })
  @ValidateNested()
  @Type(() => ProjectCreateNestedManyWithoutCityHallsInput)
  @IsOptional()
  @Field(() => ProjectCreateNestedManyWithoutCityHallsInput, {
    nullable: true,
  })
  projects?: ProjectCreateNestedManyWithoutCityHallsInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutCityHallsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutCityHallsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutCityHallsInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutCityHallsInput;
}

export { CityHallCreateInput as CityHallCreateInput };
