/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CityHallWhereUniqueInput } from "../../cityHall/base/CityHallWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { RemarkUpdateManyWithoutUsersInput } from "./RemarkUpdateManyWithoutUsersInput";
import { EnumUserRole } from "./EnumUserRole";
import { EnumVehicleType } from "./EnumVehicleType";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CityHallWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CityHallWhereUniqueInput)
  @IsOptional()
  @Field(() => CityHallWhereUniqueInput, {
    nullable: true,
  })
  cityHall?: CityHallWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => RemarkUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RemarkUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RemarkUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  remarks?: RemarkUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @IsOptional()
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?: "admin" | "dashboard_user" | "app_user" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    enum: EnumVehicleType,
    description: "Type of vehicle assigned to the user",
    example: "passenger_cars",
  })
  @IsEnum(EnumVehicleType)
  @IsOptional()
  @Field(() => EnumVehicleType, {
    nullable: true,
  })
  vehicleType?: "passenger_cars" | "garbage_truck" | "bus" | "police_vehicles" | "other" | null;

  @ApiProperty({
    required: false,
    type: String,
    description: "Custom vehicle type when 'other' is selected",
    example: "Ambulance",
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vehicleTypeOther?: string | null;
}

export { UserUpdateInput as UserUpdateInput };
