/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CityHall } from "../../cityHall/base/CityHall";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsBoolean,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Remark } from "../../remark/base/Remark";
import { EnumUserRole } from "./EnumUserRole";
import { EnumVehicleType } from "./EnumVehicleType";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";

@ObjectType()
class User {
  @ApiProperty({
    required: false,
    type: () => CityHall,
  })
  @ValidateNested()
  @Type(() => CityHall)
  @IsOptional()
  cityHall?: CityHall | null;

  @ApiProperty({
    required: false,
    type: () => CityHall,
    description: "Alias for cityHall - same data, different name for frontend"
  })
  @ValidateNested()
  @Type(() => CityHall)
  @IsOptional()
  entity?: CityHall | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive!: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Remark],
  })
  @ValidateNested()
  @Type(() => Remark)
  @IsOptional()
  remarks?: Array<Remark>;

  @ApiProperty({
    required: false,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @IsOptional()
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?: "admin" | "dashboard_user" | "app_user" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    enum: EnumVehicleType,
    description: "Type of vehicle assigned to the user",
    example: "passenger_cars",
  })
  @IsEnum(EnumVehicleType)
  @IsOptional()
  @Field(() => EnumVehicleType, {
    nullable: true,
  })
  vehicleType?: "passenger_cars" | "garbage_truck" | "bus" | "police_vehicles" | "other" | null;

  @ApiProperty({
    required: false,
    type: String,
    description: "Custom vehicle type when 'other' is selected",
    example: "Ambulance",
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  vehicleTypeOther?: string | null;
}

export { User as User };
