/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { Project } from "../../project/base/Project";
import { Remark } from "../../remark/base/Remark";

@ObjectType()
class Survey {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  assignedUser!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endTime!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => Project,
  })
  @ValidateNested()
  @Type(() => Project)
  @IsOptional()
  project?: Project | null;

  @ApiProperty({
    required: false,
    type: () => [Remark],
  })
  @ValidateNested()
  @Type(() => Remark)
  @IsOptional()
  @Field(() => [Remark], {
    nullable: true,
  })
  remarks?: Remark[] | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  remarksText!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status!: string | null;

  @ApiProperty({
    required: false,
    description: "GeoJSON LineString or MultiLineString geometry for map display",
    example: { type: "LineString", coordinates: [[-9.1393, 38.7223], [-9.1400, 38.7230]] },
  })
  @IsOptional()
  @Field(() => Object, {
    nullable: true,
  })
  geometryJson!: any | null;

  @ApiProperty({
    required: false,
    description: "Bounding box [minLng, minLat, maxLng, maxLat]",
    example: [-9.1400, 38.7223, -9.1393, 38.7230],
  })
  @IsOptional()
  @Field(() => Object, {
    nullable: true,
  })
  bbox!: any | null;

  @ApiProperty({
    required: false,
    description: "Average eIRI (International Roughness Index) value",
    example: 2.5,
    type: Number,
  })
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  eIriAvg!: number | null;

  @ApiProperty({
    required: false,
    description: "Length of the survey in meters",
    example: 1250.5,
    type: Number,
  })
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  lengthMeters!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Survey as Survey };
