/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RoutePointService } from "../routePoint.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RoutePointCreateInput } from "./RoutePointCreateInput";
import { RoutePoint } from "./RoutePoint";
import { RoutePointFindManyArgs } from "./RoutePointFindManyArgs";
import { RoutePointWhereUniqueInput } from "./RoutePointWhereUniqueInput";
import { RoutePointUpdateInput } from "./RoutePointUpdateInput";
import { HazardFindManyArgs } from "../../hazard/base/HazardFindManyArgs";
import { Hazard } from "../../hazard/base/Hazard";
import { HazardWhereUniqueInput } from "../../hazard/base/HazardWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RoutePointControllerBase {
  constructor(
    protected readonly service: RoutePointService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RoutePoint })
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRoutePoint(
    @common.Body() data: RoutePointCreateInput
  ): Promise<RoutePoint> {
    return await this.service.createRoutePoint({
      data: {
        ...data,

        project: data.project
          ? {
              connect: data.project,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        frameNumber: true,
        id: true,
        latitude: true,
        longitude: true,

        project: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RoutePoint] })
  @ApiNestedQuery(RoutePointFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async routePoints(@common.Req() request: Request): Promise<RoutePoint[]> {
    const args = plainToClass(RoutePointFindManyArgs, request.query);
    return this.service.routePoints({
      ...args,
      select: {
        createdAt: true,
        frameNumber: true,
        id: true,
        latitude: true,
        longitude: true,

        project: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RoutePoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async routePoint(
    @common.Param() params: RoutePointWhereUniqueInput
  ): Promise<RoutePoint | null> {
    const result = await this.service.routePoint({
      where: params,
      select: {
        createdAt: true,
        frameNumber: true,
        id: true,
        latitude: true,
        longitude: true,

        project: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RoutePoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRoutePoint(
    @common.Param() params: RoutePointWhereUniqueInput,
    @common.Body() data: RoutePointUpdateInput
  ): Promise<RoutePoint | null> {
    try {
      return await this.service.updateRoutePoint({
        where: params,
        data: {
          ...data,

          project: data.project
            ? {
                connect: data.project,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          frameNumber: true,
          id: true,
          latitude: true,
          longitude: true,

          project: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RoutePoint })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRoutePoint(
    @common.Param() params: RoutePointWhereUniqueInput
  ): Promise<RoutePoint | null> {
    try {
      return await this.service.deleteRoutePoint({
        where: params,
        select: {
          createdAt: true,
          frameNumber: true,
          id: true,
          latitude: true,
          longitude: true,

          project: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/hazards")
  @ApiNestedQuery(HazardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Hazard",
    action: "read",
    possession: "any",
  })
  async findHazards(
    @common.Req() request: Request,
    @common.Param() params: RoutePointWhereUniqueInput
  ): Promise<Hazard[]> {
    const query = plainToClass(HazardFindManyArgs, request.query);
    const results = await this.service.findHazards(params.id, {
      ...query,
      select: {
        createdAt: true,
        createdBy: true,
        description: true,
        id: true,
        imageUrl: true,
        latitude: true,
        longitude: true,

        project: {
          select: {
            id: true,
          },
        },

        routePoint: {
          select: {
            id: true,
          },
        },

        severity: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/hazards")
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "update",
    possession: "any",
  })
  async connectHazards(
    @common.Param() params: RoutePointWhereUniqueInput,
    @common.Body() body: HazardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hazards: {
        connect: body,
      },
    };
    await this.service.updateRoutePoint({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/hazards")
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "update",
    possession: "any",
  })
  async updateHazards(
    @common.Param() params: RoutePointWhereUniqueInput,
    @common.Body() body: HazardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hazards: {
        set: body,
      },
    };
    await this.service.updateRoutePoint({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/hazards")
  @nestAccessControl.UseRoles({
    resource: "RoutePoint",
    action: "update",
    possession: "any",
  })
  async disconnectHazards(
    @common.Param() params: RoutePointWhereUniqueInput,
    @common.Body() body: HazardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      hazards: {
        disconnect: body,
      },
    };
    await this.service.updateRoutePoint({
      where: params,
      data,
      select: { id: true },
    });
  }
}
